baseURL = "https://sunthera.github.io/"
languageCode = "en-us"
title = "Sunthera"
theme = "anubis"
disqusShortname = "suntera-website"
enableRobotsTXT =  true

[taxonomies]
tag = "tags"

[markup]

[markup.highlight]
anchorLineNos = true
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "tango"
# style = "trac"
tabWidth = 2

[author]
name = "Dmitry"

[params]
subtitle = "Notes"
customCSS = ["/css/kustomization.css"]
# style = "auto"
readMore = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1
